export const ROUTES = {
  home: "/",
  login: "/login",
  register: "/register",
  dashboard: "/dashboard",
  prompts: "/prompts",
  pieces: "/pieces",
  compose: "/compose",
  collections: "/collections",
  explore: "/explore",
  settings: "/settings",
  support: "/support",
  privacy: "/privacy",
  terms: "/terms",
} as const;
